#!/bin/bash

# update system
sudo dnf upgrade -y

# deault nautilus view
rm -Rf .local/share/gvfs-metadata
gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'

# install code
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
sudo dnf check-update
sudo dnf install code -y

# install oh-my-zsh
sudo dnf install -y vim fontawesome-fonts powerline tmux-powerline powerline-fonts
